### ISSUE TITLE
have no packageName,can not import 

### ISSUE THREAD

**Issue by Liloupar** [shuza/kt-jsonq#1]

**Comment by shuza** [comment]
Its under he root package. Have you added Jetpack to the repositories?
`maven { url "https://jitpack.io" }`

**Comment by Liloupar** [comment]
yes, i have already added it,
but,in android studio 3.1.2 i can not import JsonQ by cmd + enter.
it still hint 'unresolved reference JsonQ' 
thx

**Comment by shuza** [comment]
I have updated the package. Now it is under `com.shuza.jsonq` package. There are also few other changes. Please have a look on the updated doc and don't forget to include update version `v1.0`

**Comment by Liloupar** [comment]
Thanks for your work, this is super helpful!
